#!/usr/bin/bash

set -eu
# Do the builds & run tests. On Linux.
# Runs inside the .git directory where THIS script is located.

gitdir=$(cd $(dirname $0); git rev-parse --show-toplevel)

build_run_tests()
{
    # invoked where?
    ninja -v
    find -name \*.gcda -exec rm -r '{}' \;
    cd test; ctest
}



(
    set -eu
    cd $gitdir
    mkdir ${dir:=build.gcc}
    pushd $dir
    cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja  ../  -DFORCE_COLORED_OUTPUT=1 -DCMAKE_CXX_COMPILER=g++
    build_run_tests
    popd
)


(
    cd $gitdir
    mkdir ${dir:=build.clang}
    cd $dir
    cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja  ../  -DFORCE_COLORED_OUTPUT=1 -DCMAKE_CXX_COMPILER=clang++

    build_run_tests

    rm -f **/*gcda
)


( cd $gitdir
  tmpdir=$gitdir/tmp
  # cmake install --install . --prefix tmp -v
  pushd build.gcc
  DESTDIR=$tmpdir cmake --install .   -v
  DESTDIR=$tmpdir ninja -v install
)
